version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Build started"
      - echo "Starting linting"
      
  build:
    commands:
      - echo "Running Linting..."
      - npm run lint

  post_build:
    commands:
      - echo "Build Completed Successfully."

artifacts:
  files:
    - '**/*'
